// =============================================================================
// tb_uart_rw_veer.v
//
// Testbench: VeeR EL2 SoC — UART Read/Write Verification
//
// ─── Purpose ────────────────────────────────────────────────────────────────
//   Verifies the full SoC (VeeR EL2 + AXI interconnect + I2C + AES + UART)
//   by executing uart_rw.hex on the VeeR core and checking the UART output.
//
// ─── DUT ────────────────────────────────────────────────────────────────────
//   soc_top_with_veer  (VeeR EL2 + AXI-interconnect + I2C + AES + UART)
//
// ─── Firmware (uart_rw.hex) logic ───────────────────────────────────────────
//   1. uart_init()   → configure UART (8N1, 115200 baud)
//   2. uart_putc('A') → transmit 0x41
//   3. uart_getc()   → receive byte via UART loopback (TX→RX)
//   4. if rx == 'A'  → uart_putc('P')   // PASS
//      else          → uart_putc('F')   // FAIL
//   5. while(1) spin
//
// ─── Test strategy ──────────────────────────────────────────────────────────
//   • Assert reset for 20 clk cycles, release
//   • UART TX is looped back to UART RX (combinatorial: uart_rx_i = uart_tx_o)
//   • UART byte deserializer samples uart_tx_o at 115200 baud
//   • Expected byte sequence on TX: 'A' (0x41) then 'P' (0x50)
//     - First byte  'A' = firmware transmitting the test character
//     - Second byte 'P' = firmware confirmed loopback → PASS
//     - Second byte 'F' = loopback mismatch           → FAIL
//   • The TB prints SIMULATION PASS or SIMULATION FAIL accordingly
//
// ─── ICCM firmware loading ───────────────────────────────────────────────────
//   VeeR EL2 (AXI4 mode, ICCM enabled) fetches instructions from the on-chip
//   ICCM at 0xEE000000.  The ICCM banks are interface-based SRAMs accessed
//   through el2_mem_if; they are NOT bare reg arrays that $readmemh can
//   address directly from the TB level.
//
//   Two supported load methods (choose via compile-time define):
//
//   Method A — +define+ICCM_HIER_LOAD (default when using run_uart_rw_veer.f)
//     $readmemh into el2_ifu_iccm_mem's internal RAM via hierarchical path.
//     Works with VCS if the SRAM is implemented as a reg array.
//     Hierarchical path:
//       dut.u_veer.veer.mem.iccm.mem.iccm_bank[*].mem_bank.ram
//     (adjust if VeeR config changes bank count or naming)
//
//   Method B — No define: TB prints a warning; firmware must be pre-loaded
//     via the DMA AXI port or the ICCM_HEX_FILE RTL parameter.
//
//   The hex file is Verilog $readmemh format (plain hex, one 32-bit word per
//   line, no addresses).  uart_rw.hex is generated by the RISC-V toolchain
//   with objcopy --output-target=verilog.
//
// ─── Clock / address map ────────────────────────────────────────────────────
//   CLK   = 100 MHz (10 ns period)
//   BAUD  = 115200  → bit period ≈ 8680 ns
//   ICCM  base = 0xEE00_0000  (RV_ICCM_SADR from common_defines.vh)
//   UART  base = 0x0200_0000
//   Reset vec  = 0x8000_0000  (drives rst_vec input to wrapper)
//
// ─── Pass/fail criteria ─────────────────────────────────────────────────────
//   PASS if  the 2nd UART byte == 'P' (0x50)
//   FAIL if  the 2nd UART byte == 'F' (0x46)
//   FAIL if  simulation timeout (2 ms) without seeing both bytes
//
// =============================================================================



module tb_uart_rw_veer;

    // =========================================================================
    // Parameters
    // =========================================================================
    localparam DW            = 32;
    localparam AW            = 32;
    localparam IDW           = 8;
    localparam SW            = DW/8;

    localparam CLK_HALF_NS   = 5;               // 5 ns → 100 MHz
    localparam SIM_TIMEOUT   = 2_000_000;       // 2 ms in ns

    // UART baud rate timing (115200 baud @ 100 MHz)
    // Bit period = 100e6 / 115200 = 868.1 clk cycles = 8680 ns
    localparam BAUD_NS       = 8680;
    localparam BAUD_HALF_NS  = BAUD_NS / 2;

    // =========================================================================
    // VeeR boot constants
    // =========================================================================
    // Reset vector = 0xEE000000 (ICCM base address — where firmware is loaded)
    // The reset vector input to el2_veer_wrapper is [31:1] (byte-addr >> 1)
    localparam [31:1] RESET_VEC = 31'h7700_0000; // 0xEE000000 >> 1
    localparam [31:1] NMI_VEC   = 31'h7700_0100;
    localparam [31:1] JTAG_ID   = 31'h0000_0001;

    // =========================================================================
    // DUT signals
    // =========================================================================
    reg         clk;
    reg         rst_n;

    // VeeR control
    wire [31:1] rst_vec    = RESET_VEC;
    wire [31:1] nmi_vec    = NMI_VEC;
    wire [31:1] jtag_id    = JTAG_ID;
    wire        nmi_int    = 1'b0;

    // JTAG — tie off (not used in functional verification)
    wire        jtag_tck   = 1'b0;
    wire        jtag_tms   = 1'b1;  // TMS=1 keeps TAP in reset state
    wire        jtag_tdi   = 1'b0;
    wire        jtag_tdo;

    // ── Spare AXI master (s01) — tied off ────────────────────────────────────
    wire [IDW-1:0]   s01_axi_awid    = {IDW{1'b0}};
    wire [AW-1:0]    s01_axi_awaddr  = {AW{1'b0}};
    wire [7:0]       s01_axi_awlen   = 8'h0;
    wire [2:0]       s01_axi_awsize  = 3'h0;
    wire [1:0]       s01_axi_awburst = 2'b01;
    wire             s01_axi_awlock  = 1'b0;
    wire [3:0]       s01_axi_awcache = 4'h0;
    wire [2:0]       s01_axi_awprot  = 3'h0;
    wire [3:0]       s01_axi_awqos   = 4'h0;
    wire             s01_axi_awvalid = 1'b0;
    wire [DW-1:0]    s01_axi_wdata   = {DW{1'b0}};
    wire [SW-1:0]    s01_axi_wstrb   = {SW{1'b0}};
    wire             s01_axi_wlast   = 1'b0;
    wire             s01_axi_wvalid  = 1'b0;
    wire             s01_axi_bready  = 1'b0;
    wire [IDW-1:0]   s01_axi_arid    = {IDW{1'b0}};
    wire [AW-1:0]    s01_axi_araddr  = {AW{1'b0}};
    wire [7:0]       s01_axi_arlen   = 8'h0;
    wire [2:0]       s01_axi_arsize  = 3'h0;
    wire [1:0]       s01_axi_arburst = 2'b01;
    wire             s01_axi_arlock  = 1'b0;
    wire [3:0]       s01_axi_arcache = 4'h0;
    wire [2:0]       s01_axi_arprot  = 3'h0;
    wire [3:0]       s01_axi_arqos   = 4'h0;
    wire             s01_axi_arvalid = 1'b0;
    wire             s01_axi_rready  = 1'b0;

    // s01 outputs (ignored)
    wire             s01_axi_awready;
    wire             s01_axi_wready;
    wire [IDW-1:0]   s01_axi_bid;
    wire [1:0]       s01_axi_bresp;
    wire             s01_axi_bvalid;
    wire             s01_axi_arready;
    wire [IDW-1:0]   s01_axi_rid;
    wire [DW-1:0]    s01_axi_rdata;
    wire [1:0]       s01_axi_rresp;
    wire             s01_axi_rlast;
    wire             s01_axi_rvalid;

    // ── I2C — open-drain loopback (pulled high when bus inactive) ─────────────
    wire scl_pad_o, scl_padoen_o;
    wire sda_pad_o, sda_padoen_o;
    wire i2c_irq;
    // Simulate open-drain: when padoen=0 the pad drives pad_o, else pulled high
    wire scl_pad_i = scl_padoen_o ? 1'b1 : scl_pad_o;
    wire sda_pad_i = sda_padoen_o ? 1'b1 : sda_pad_o;

    // ── UART ─────────────────────────────────────────────────────────────────
    wire uart_tx_o;
    wire uart_irq;
    reg  uart_rx_i;

    // ── VeeR trace outputs ────────────────────────────────────────────────────
    wire [31:0] trace_rv_i_insn_ip;
    wire [31:0] trace_rv_i_address_ip;
    wire        trace_rv_i_valid_ip;
    wire        trace_rv_i_exception_ip;
    wire [4:0]  trace_rv_i_ecause_ip;
    wire        trace_rv_i_interrupt_ip;
    wire [31:0] trace_rv_i_tval_ip;

    // =========================================================================
    // Clock generation  — 100 MHz
    // =========================================================================
    initial clk = 1'b0;
    always #CLK_HALF_NS clk = ~clk;

    // =========================================================================
    // UART TX → RX loopback  (combinatorial, zero delay)
    // The CPU transmits a byte on uart_tx_o; the UART receiver reads it
    // back on uart_rx_i to implement the loopback required by uart_rw.c.
    // =========================================================================
    always @(*) uart_rx_i = uart_tx_o;

    // =========================================================================
    // DUT instantiation
    // =========================================================================
    soc_top_with_veer #(
        .DATA_WIDTH (DW),
        .ADDR_WIDTH (AW),
        .ID_WIDTH   (IDW)
    ) dut (
        // ── Clock / reset ────────────────────────────────────────────────
        .clk              (clk),
        .rst_n            (rst_n),

        // ── VeeR control ─────────────────────────────────────────────────
        .rst_vec          (rst_vec),
        .nmi_vec          (nmi_vec),
        .jtag_id          (jtag_id),
        .nmi_int          (nmi_int),

        // ── JTAG ─────────────────────────────────────────────────────────
        .jtag_tck         (jtag_tck),
        .jtag_tms         (jtag_tms),
        .jtag_tdi         (jtag_tdi),
        .jtag_tdo         (jtag_tdo),

        // ── Spare AXI master (s01) — tied off ────────────────────────────
        .s01_axi_awid     (s01_axi_awid),
        .s01_axi_awaddr   (s01_axi_awaddr),
        .s01_axi_awlen    (s01_axi_awlen),
        .s01_axi_awsize   (s01_axi_awsize),
        .s01_axi_awburst  (s01_axi_awburst),
        .s01_axi_awlock   (s01_axi_awlock),
        .s01_axi_awcache  (s01_axi_awcache),
        .s01_axi_awprot   (s01_axi_awprot),
        .s01_axi_awqos    (s01_axi_awqos),
        .s01_axi_awvalid  (s01_axi_awvalid),
        .s01_axi_awready  (s01_axi_awready),
        .s01_axi_wdata    (s01_axi_wdata),
        .s01_axi_wstrb    (s01_axi_wstrb),
        .s01_axi_wlast    (s01_axi_wlast),
        .s01_axi_wvalid   (s01_axi_wvalid),
        .s01_axi_wready   (s01_axi_wready),
        .s01_axi_bid      (s01_axi_bid),
        .s01_axi_bresp    (s01_axi_bresp),
        .s01_axi_bvalid   (s01_axi_bvalid),
        .s01_axi_bready   (s01_axi_bready),
        .s01_axi_arid     (s01_axi_arid),
        .s01_axi_araddr   (s01_axi_araddr),
        .s01_axi_arlen    (s01_axi_arlen),
        .s01_axi_arsize   (s01_axi_arsize),
        .s01_axi_arburst  (s01_axi_arburst),
        .s01_axi_arlock   (s01_axi_arlock),
        .s01_axi_arcache  (s01_axi_arcache),
        .s01_axi_arprot   (s01_axi_arprot),
        .s01_axi_arqos    (s01_axi_arqos),
        .s01_axi_arvalid  (s01_axi_arvalid),
        .s01_axi_arready  (s01_axi_arready),
        .s01_axi_rid      (s01_axi_rid),
        .s01_axi_rdata    (s01_axi_rdata),
        .s01_axi_rresp    (s01_axi_rresp),
        .s01_axi_rlast    (s01_axi_rlast),
        .s01_axi_rvalid   (s01_axi_rvalid),
        .s01_axi_rready   (s01_axi_rready),

        // ── I2C ─────────────────────────────────────────────────────────
        .scl_pad_i        (scl_pad_i),
        .scl_pad_o        (scl_pad_o),
        .scl_padoen_o     (scl_padoen_o),
        .sda_pad_i        (sda_pad_i),
        .sda_pad_o        (sda_pad_o),
        .sda_padoen_o     (sda_padoen_o),
        .i2c_irq          (i2c_irq),

        // ── UART ─────────────────────────────────────────────────────────
        .uart_tx_o        (uart_tx_o),
        .uart_rx_i        (uart_rx_i),
        .uart_irq         (uart_irq),

        // ── VeeR trace ───────────────────────────────────────────────────
        .trace_rv_i_insn_ip      (trace_rv_i_insn_ip),
        .trace_rv_i_address_ip   (trace_rv_i_address_ip),
        .trace_rv_i_valid_ip     (trace_rv_i_valid_ip),
        .trace_rv_i_exception_ip (trace_rv_i_exception_ip),
        .trace_rv_i_ecause_ip    (trace_rv_i_ecause_ip),
        .trace_rv_i_interrupt_ip (trace_rv_i_interrupt_ip),
        .trace_rv_i_tval_ip      (trace_rv_i_tval_ip)
    );

    // =========================================================================
    // Firmware loading into VeeR ICCM
    // =========================================================================
    //
    // VeeR EL2 with ICCM enabled fetches instructions from the Instruction
    // Closely-Coupled Memory (ICCM) at 0xEE000000.
    //
    // In RTL simulation the ICCM is implemented as banked register arrays
    // inside el2_ifu_iccm_mem.  We load the firmware hex file into those
    // arrays using $readmemh with a hierarchical path.
    //
    // Hierarchical path (VeeR EL2, default 4-bank ICCM config):
    //   dut.u_veer.veer.mem.iccm.mem.iccm_bank[N].mem_bank.ram_data
    //
    // The hex file (uart_rw.hex) must be in Verilog $readmemh plain-hex
    // format: one 32-bit word per line, most-significant byte first,
    // starting from ICCM offset 0 (absolute 0xEE000000).
    //
    // Plusarg:  +hex_file+<path>      override hex file path
    // Default:  ../scripts/uart_rw.hex  (relative to run/ directory)
    // -------------------------------------------------------------------------

    // Number of ICCM banks (default VeeR config = 4; must match pt.ICCM_NUM_BANKS)
    // If VeeR was configured with a different count, update ICCM_NUM_BANKS.
    localparam ICCM_NUM_BANKS = 4;

    string  hex_path;
    string  hex_bank0, hex_bank1, hex_bank2, hex_bank3;

    initial begin
        // ── Resolve firmware hex path ──────────────────────────────────────
        // +hex_file+<path>  points to uart_rw_iccm_words.hex (flat 32-bit words).
        // Per-bank interleaved hex files (uart_rw_bankN.hex) are expected in the
        // same directory — generated by run_uart_rw_veer.sh before simulation.
        if (!$value$plusargs("hex_file+%s", hex_path))
            hex_path = "../scripts/uart_rw_iccm_words.hex";

        // Build per-bank file paths: same directory, fixed names
        begin : build_bank_paths
            string base_dir;
            integer ci, last_slash;
            last_slash = -1;
            for (ci = 0; ci < hex_path.len(); ci = ci + 1)
                if (hex_path.getc(ci) == "/") last_slash = ci;
            if (last_slash >= 0)
                base_dir = hex_path.substr(0, last_slash);
            else
                base_dir = ".";
            hex_bank0 = {base_dir, "/uart_rw_bank0.hex"};
            hex_bank1 = {base_dir, "/uart_rw_bank1.hex"};
            hex_bank2 = {base_dir, "/uart_rw_bank2.hex"};
            hex_bank3 = {base_dir, "/uart_rw_bank3.hex"};
        end

        $display("================================================================");
        $display(" TB: tb_uart_rw_veer");
        $display(" DUT: soc_top_with_veer  (VeeR EL2 + I2C + AES + UART)");
        $display(" Firmware flat hex : %s", hex_path);
        $display(" ICCM bank0 hex    : %s", hex_bank0);
        $display(" Test: UART loopback  —  expect TX sequence: 'A', 'P'");
        $display("================================================================");

`ifdef ICCM_HIER_LOAD
        // ── Method A: direct $readmemh into ICCM register array ───────────
        //
        // VeeR EL2 ICCM bank interleaving (ICCM_BANK_HI=3, ICCM_BANK_INDEX_LO=4):
        //   Word index i from ICCM base address:
        //     bank  =  i & 3          (addr[3:2])
        //     row   =  i >> 2         (addr[15:4])
        //
        //   Each bank's ram_core[row] must contain the correct interleaved word:
        //     bank0: words[0], words[4],  words[8],  ...   (rows 0,1,2,...)
        //     bank1: words[1], words[5],  words[9],  ...
        //     bank2: words[2], words[6],  words[10], ...
        //     bank3: words[3], words[7],  words[11], ...
        //
        //   The per-bank hex files are pre-generated by run_uart_rw_veer.sh.
        //   Loading the flat hex identically into all banks is WRONG because
        //   ram_core[0] of bank1 would hold words[0] instead of words[1].
        //
        $display("[TB] Loading ICCM per-bank interleaved hex via hierarchical $readmemh ...");
        $readmemh(hex_bank0, dut.Gen_iccm_enable.iccm_loop[0].iccm_bank.ram_core);
        $readmemh(hex_bank1, dut.Gen_iccm_enable.iccm_loop[1].iccm_bank.ram_core);
        $readmemh(hex_bank2, dut.Gen_iccm_enable.iccm_loop[2].iccm_bank.ram_core);
        $readmemh(hex_bank3, dut.Gen_iccm_enable.iccm_loop[3].iccm_bank.ram_core);

        // ── Fix up ECC for every loaded word ──────────────────────────────
        // VeeR EL2 uses a 7-bit SECDED Hamming code over 32 data bits.
        // Without correct ECC the core raises double-bit error traps and stalls.
        begin : ecc_fixup
            integer idx;
            reg [31:0] d;
            reg [6:0]  e;
            for (idx = 0; idx < `RV_ICCM_ROWS; idx = idx + 1) begin
                d = dut.Gen_iccm_enable.iccm_loop[0].iccm_bank.ram_core[idx][31:0];
                e = rvecc32(d);
                dut.Gen_iccm_enable.iccm_loop[0].iccm_bank.ram_core[idx][38:32] = e;
                d = dut.Gen_iccm_enable.iccm_loop[1].iccm_bank.ram_core[idx][31:0];
                e = rvecc32(d);
                dut.Gen_iccm_enable.iccm_loop[1].iccm_bank.ram_core[idx][38:32] = e;
                d = dut.Gen_iccm_enable.iccm_loop[2].iccm_bank.ram_core[idx][31:0];
                e = rvecc32(d);
                dut.Gen_iccm_enable.iccm_loop[2].iccm_bank.ram_core[idx][38:32] = e;
                d = dut.Gen_iccm_enable.iccm_loop[3].iccm_bank.ram_core[idx][31:0];
                e = rvecc32(d);
                dut.Gen_iccm_enable.iccm_loop[3].iccm_bank.ram_core[idx][38:32] = e;
            end
        end
        $display("[TB] ICCM per-bank load + ECC fix-up complete.");
        // Sanity check: first word of each bank
        $display("[TB] bank0[0]=0x%08h (expect 0x02050117 = auipc sp,0x2050 @ EE000000)",
            dut.Gen_iccm_enable.iccm_loop[0].iccm_bank.ram_core[0][31:0]);
        $display("[TB] bank1[0]=0x%08h (expect 0x00010113 = mv sp,sp          @ EE000004)",
            dut.Gen_iccm_enable.iccm_loop[1].iccm_bank.ram_core[0][31:0]);
        $display("[TB] bank2[0]=0x%08h (expect 0x02040297 = auipc t0,...      @ EE000008)",
            dut.Gen_iccm_enable.iccm_loop[2].iccm_bank.ram_core[0][31:0]);
        $display("[TB] bank3[0]=0x%08h (expect 0xff828293 = addi t0,t0,-8    @ EE00000C)",
            dut.Gen_iccm_enable.iccm_loop[3].iccm_bank.ram_core[0][31:0]);
`else
        // ── Method B: RTL define-based load ───────────────────────────────
        // Compile with +define+ICCM_HEX_FILE=\"path/to/uart_rw.hex\"
        // The el2_ifu_iccm_mem behavioral model picks this up at init time.
        $display("[TB] WARNING: ICCM_HIER_LOAD not defined.");
        $display("[TB] Ensure firmware is loaded via +define+ICCM_HEX_FILE.");
        $display("[TB] Alternatively, add +define+ICCM_HIER_LOAD to compile flags.");
`endif
    end

    // =========================================================================
    // Reset sequence  — hold rst_n low for 20 clock cycles
    // =========================================================================
    initial begin
        rst_n = 1'b0;
        repeat(20) @(posedge clk);
        @(negedge clk);
        rst_n = 1'b1;
        $display("[TB] rst_n released at time %0t ns", $time);
    end

    // =========================================================================
    // Waveform dump  (Verdi FSDB)
    // =========================================================================
   /* initial begin
    $fsdbDumpfile("dumpuart.fsdb");
    $fsdbDumpvars("+all");
    $fsdbDumpSVA();
    $fsdbDumpMDA();
    end*/
    // =========================================================================
    // VeeR instruction trace monitor
    // =========================================================================
    // Prints every committed instruction: time, PC, encoding, and exception flag.
    // Useful to see where the CPU is in the firmware.
    always @(posedge clk) begin
        if (trace_rv_i_valid_ip && rst_n) begin
            $display("[TRACE] t=%0t ns  PC=0x%08h  INSN=0x%08h  %s",
                $time,
                trace_rv_i_address_ip,
                trace_rv_i_insn_ip,
                trace_rv_i_exception_ip
                    ? $sformatf("EXCEPTION cause=0x%0h tval=0x%08h",
                                trace_rv_i_ecause_ip,
                                trace_rv_i_tval_ip)
                    : "");
        end
    end

    // =========================================================================
    // AXI UART-region write monitor
    // =========================================================================
    // Fires on BOTH AW and W channel handshakes to capture addr and data
    // accurately (AXI allows W to arrive after AW).
    // Also monitors the actual data reaching the UART slave input directly.
    always @(posedge clk) begin
        if (rst_n) begin
            // AW channel: capture address
            if (dut.lsu_axi_awvalid && dut.lsu_axi_awready &&
                dut.lsu_axi_awaddr[31:24] == 8'h02)
                $display("[AXI-AW] t=%0t ns  UART AW addr=0x%08h",
                         $time, dut.lsu_axi_awaddr);
            // W channel: capture data
            if (dut.lsu_axi_wvalid && dut.lsu_axi_wready)
                $display("[AXI-W]  t=%0t ns  UART W  data=0x%016h  strb=0x%02h",
                         $time, dut.lsu_axi_wdata, dut.lsu_axi_wstrb);
            // UART slave write accepted (directly at UART input port)
            if (dut.u_soc.u_uart.u_uart.axi_wren &&
                !dut.u_soc.u_uart.u_uart.axi_sync_wren)
                $display("[UART-WR] t=%0t ns  UART reg write addr[4:2]=0x%01h  data=0x%08h  DLAB=%b",
                         $time,
                         dut.u_soc.u_uart.u_uart.axi_awaddr_i[4:2],
                         dut.u_soc.u_uart.u_uart.axi_wdata_i,
                         dut.u_soc.u_uart.u_uart.uart_dlab_int);
        end
    end

    // =========================================================================
    // UART byte deserializer
    // =========================================================================
    // Detects UART start bit on uart_tx_o, samples 8 data bits at 115200 baud,
    // then dispatches to the pass/fail checker.
    //
    // Protocol: 8N1, LSB first, idle=HIGH
    //   START   : 1 bit  low
    //   DATA[0:7]: 8 bits, LSB first
    //   STOP    : 1 bit  high
    //
    // Sampling strategy:
    //   On falling edge of uart_tx_o (start bit):
    //     wait BAUD_NS + BAUD_HALF_NS  → centre of bit[0]
    //     sample each bit BAUD_NS apart
    // -------------------------------------------------------------------------

    // Byte counter and received bytes array (we expect at most 3 bytes: A,P or A,F)
    integer  uart_byte_count;
    reg [7:0] uart_bytes [0:7];   // store up to 8 received bytes
    reg       uart_busy;          // set while sampling a byte

    // Pass/fail status
    reg test_pass;
    reg test_fail;
    reg test_done;

    initial begin
        uart_byte_count = 0;
        uart_busy       = 1'b0;
        test_pass       = 1'b0;
        test_fail       = 1'b0;
        test_done       = 1'b0;
    end

    // Deserializer process — triggered by start bit (negedge on uart_tx_o)
    always @(negedge uart_tx_o) begin
        if (!uart_busy && rst_n) begin
            integer i;
            reg [7:0] rx_byte;

            uart_busy = 1'b1;

            // Wait to the centre of the first data bit
            // (1 full baud period from start-bit edge, then half more)
            #(BAUD_NS + BAUD_HALF_NS);

            // Sample 8 data bits (LSB first)
            rx_byte = 8'h00;
            for (i = 0; i < 8; i = i + 1) begin
                rx_byte[i] = uart_tx_o;
                if (i < 7) #BAUD_NS;
            end

            // Wait for stop bit before accepting next byte
            #BAUD_NS;

            // Log the received byte
            $display("[UART] t=%0t ns  RX byte[%0d] = 0x%02h  ('%s')",
                     $time, uart_byte_count, rx_byte,
                     (rx_byte >= 8'h20 && rx_byte < 8'h7f)
                         ? {1'b0, rx_byte}  // printable ASCII
                         : 8'h2e);          // '.' for non-printable

            // Store byte
            if (uart_byte_count < 8)
                uart_bytes[uart_byte_count] = rx_byte;
            uart_byte_count = uart_byte_count + 1;

            // ── Pass/fail decision ─────────────────────────────────────────
            //
            // Byte 0 = 'A' (0x41) : test character transmitted by firmware
            // Byte 1 = 'P' (0x50) : firmware received 'A' back → PASS
            //        = 'F' (0x46) : firmware received wrong byte → FAIL

            if (uart_byte_count == 1) begin
                // First byte should be 'A'
                if (rx_byte == 8'h41) begin
                    $display("[CHECK] t=%0t ns  Byte 0 = 'A' — test char transmitted OK",
                             $time);
                end else begin
                    $display("[CHECK] t=%0t ns  WARNING: Byte 0 = 0x%02h (expected 0x41 'A')",
                             $time, rx_byte);
                end
            end

            if (uart_byte_count == 2) begin
                // Second byte is pass/fail indicator
                if (rx_byte == 8'h50) begin  // 'P'
                    $display("[RESULT] ================================================================");
                    $display("[RESULT]  SIMULATION PASS");
                    $display("[RESULT]  VeeR executed uart_rw.hex successfully.");
                    $display("[RESULT]  UART loopback verified: TX='A', RX='A', response='P'");
                    $display("[RESULT] ================================================================");
                    test_pass = 1'b1;
                    test_done = 1'b1;
                end else if (rx_byte == 8'h46) begin  // 'F'
                    $display("[RESULT] ================================================================");
                    $display("[RESULT]  SIMULATION FAIL");
                    $display("[RESULT]  Firmware received wrong byte on loopback.");
                    $display("[RESULT]  Expected 'A' (0x41), got 0x%02h", uart_bytes[0]);
                    $display("[RESULT] ================================================================");
                    test_fail = 1'b1;
                    test_done = 1'b1;
                end else begin
                    $display("[CHECK] t=%0t ns  Unexpected byte 1 = 0x%02h", $time, rx_byte);
                end
            end

            uart_busy = 1'b0;
        end
    end

    // =========================================================================
    // Simulation termination after pass/fail
    // =========================================================================
    always @(posedge test_done) begin
        // Give 10 extra clk cycles for waveform flush
        repeat(10) @(posedge clk);
        $finish;
    end

    // =========================================================================
    // Simulation timeout watchdog
    // =========================================================================
    initial begin
        #SIM_TIMEOUT;
        $display("[RESULT] ================================================================");
        $display("[RESULT]  SIMULATION TIMEOUT at %0t ns", $time);
        if (uart_byte_count == 0)
            $display("[RESULT]  No UART bytes received. Check: ICCM load, reset vector, UART baud.");
        else if (uart_byte_count == 1)
            $display("[RESULT]  Only 1 UART byte received (0x%02h). Loopback may be broken.",
                     uart_bytes[0]);
        else
            $display("[RESULT]  %0d UART bytes received but no P/F seen.", uart_byte_count);
        $display("[RESULT]  Check waveform: dump_uart_rw.fsdb");
        $display("[RESULT] ================================================================");
        $finish;
    end

    // =========================================================================
    // Additional diagnostic: track total AXI transactions to UART region
    // =========================================================================
    integer uart_axi_wr_count;
    integer uart_axi_rd_count;

    initial begin
        uart_axi_wr_count = 0;
        uart_axi_rd_count = 0;
    end

    always @(posedge clk) begin
        if (rst_n) begin
            if (dut.lsu_axi_awvalid && dut.lsu_axi_awready &&
                (dut.lsu_axi_awaddr[31:24] == 8'h02))
                uart_axi_wr_count = uart_axi_wr_count + 1;

            if (dut.lsu_axi_arvalid && dut.lsu_axi_arready &&
                (dut.lsu_axi_araddr[31:24] == 8'h02)) begin
                uart_axi_rd_count = uart_axi_rd_count + 1;
                $display("[AXI-AR] t=%0t ns  UART AR addr=0x%08h  strb=0x%02h",
                         $time, dut.lsu_axi_araddr, dut.lsu_axi_wstrb);
            end
        end
    end

    // =========================================================================
    // ICCM access monitor — watch for first clken pulses via real_sram_if
    // =========================================================================
    integer iccm_access_cnt;
    initial iccm_access_cnt = 0;
    always @(posedge clk) begin
        if (rst_n && |dut.real_sram_if.iccm_clken && iccm_access_cnt < 5) begin
            $display("[ICCM] t=%0t ns  iccm_clken=0x%h  wren=0x%h  addr_b0=0x%h",
                     $time,
                     dut.real_sram_if.iccm_clken,
                     dut.real_sram_if.iccm_wren_bank,
                     dut.real_sram_if.iccm_addr_bank[0]);
            iccm_access_cnt = iccm_access_cnt + 1;
        end
    end

    // =========================================================================
    // ECC helper — matches VeeR rvecc_encode (7-bit SECDED over 32-bit data)
    // =========================================================================
    function automatic [6:0] rvecc32;
        input [31:0] din;
        reg [5:0] t;
        begin
            t[0] = din[0]^din[1]^din[3]^din[4]^din[6]^din[8]^din[10]^din[11]^din[13]^din[15]^din[17]^din[19]^din[21]^din[23]^din[25]^din[26]^din[28]^din[30];
            t[1] = din[0]^din[2]^din[3]^din[5]^din[6]^din[9]^din[10]^din[12]^din[13]^din[16]^din[17]^din[20]^din[21]^din[24]^din[25]^din[27]^din[28]^din[31];
            t[2] = din[1]^din[2]^din[3]^din[7]^din[8]^din[9]^din[10]^din[14]^din[15]^din[16]^din[17]^din[22]^din[23]^din[24]^din[25]^din[29]^din[30]^din[31];
            t[3] = din[4]^din[5]^din[6]^din[7]^din[8]^din[9]^din[10]^din[18]^din[19]^din[20]^din[21]^din[22]^din[23]^din[24]^din[25];
            t[4] = din[11]^din[12]^din[13]^din[14]^din[15]^din[16]^din[17]^din[18]^din[19]^din[20]^din[21]^din[22]^din[23]^din[24]^din[25];
            t[5] = din[26]^din[27]^din[28]^din[29]^din[30]^din[31];
            rvecc32 = {(^din[31:0])^(^t[5:0]), t[5:0]};
        end
    endfunction

endmodule
// =============================================================================
// END OF TESTBENCH
// =============================================================================
