// =============================================================================
// soc_top_with_veer.v
//
// Secure IoT Gateway SoC  –  Top-level with VeeR EL2 CPU
//
// Architecture
// ─────────────────────────────────────────────────────────────────────────────
//
//   ┌─────────────────────┐
//   │   el2_veer_wrapper  │  (VeeR EL2 RISC-V core)
//   │                     │
//   │  LSU AXI4 (64-bit)  │──[width-adapt 64→32]──►  s00 ─┐
//   │  IFU AXI4           │──► ifu_axi_stub (ICCM mode)   │
//   │  SB  AXI4           │──► tied off                    │
//   │  DMA AXI4           │◄── tied off                    │
//   └─────────────────────┘                                │
//                                                          ▼
//                                         ┌───────────────────────────┐
//                                         │ axi_interconnect_wrap_2x11│
//   s01 ◄────────────────────────────────►│  (2 masters, 11 slaves)   │
//   (top-level port – spare master)       └───────────┬───────────────┘
//                                                      │ 11 slave ports
//   Address map:                           m00 0x0000_0000  I2C  (WB bridge)
//     0x0000_0000  I2C master (Wishbone)   m01 0x0100_0000  AES
//     0x0100_0000  AES encrypt/decrypt     m02 0x0200_0000  UART
//     0x0200_0000  UART (AXI4-Lite)        m03-m10          dummy slaves
//     0x0300_0000–0x0A00_0000  reserved
//
// Bus width notes
// ─────────────────────────────────────────────────────────────────────────────
//   VeeR LSU AXI data bus is 64-bit (fixed by the core).
//   The SoC interconnect is 32-bit.
//   A thin width-adapter is inserted:
//     • On writes : only wdata[31:0] / wstrb[3:0] are forwarded.
//                   The CPU must never issue 64-bit (dword) writes to
//                   peripherals — it should use 32-bit (word) transfers.
//     • On reads  : rdata[63:32] is returned as 0x00000000 to the core.
//   This is sufficient for MMIO-only operation (no DMA/cache-line beats).
//
// IFU (instruction fetch) note
// ─────────────────────────────────────────────────────────────────────────────
//   With ICCM enabled (default config), the IFU fetches from the on-chip
//   ICCM rather than the external AXI bus.  The IFU AXI port stubs below
//   (awready/wready/arready = 0, all response channels silent) satisfy the
//   protocol while the core uses its ICCM for instruction storage.
//   To boot from external flash, replace the stubs with a real memory slave.
//
// =============================================================================

`timescale 1ns/1ps
`default_nettype none

// Pick up VeeR parameter defines generated by veer.config
// (searched via +incdir in the VCS filelist)
`include "common_defines.vh"

module soc_top_with_veer #(
    parameter DATA_WIDTH = 32,
    parameter ADDR_WIDTH = 32,
    parameter ID_WIDTH   = 8          // interconnect AXI ID width
)(
    // ── Clocks & Reset ───────────────────────────────────────────────────
    input  wire        clk,
    input  wire        rst_n,         // active-low system reset

    // ── VeeR boot / debug control ────────────────────────────────────────
    input  wire [31:1] rst_vec,       // reset (boot) vector, tie to 32'h8000_0000 in TB
    input  wire [31:1] nmi_vec,       // NMI vector
    input  wire [31:1] jtag_id,       // JTAG manufacturer ID
    input  wire        nmi_int,       // NMI input

    // ── JTAG (debug) ─────────────────────────────────────────────────────
    input  wire        jtag_tck,
    input  wire        jtag_tms,
    input  wire        jtag_tdi,
    output wire        jtag_tdo,

    // ── Spare AXI master port (s01 exposed to top) ───────────────────────
    // A second CPU or DMA can be connected here from the board-level.
    input  wire [ID_WIDTH-1:0]     s01_axi_awid,
    input  wire [ADDR_WIDTH-1:0]   s01_axi_awaddr,
    input  wire [7:0]              s01_axi_awlen,
    input  wire [2:0]              s01_axi_awsize,
    input  wire [1:0]              s01_axi_awburst,
    input  wire                    s01_axi_awlock,
    input  wire [3:0]              s01_axi_awcache,
    input  wire [2:0]              s01_axi_awprot,
    input  wire [3:0]              s01_axi_awqos,
    input  wire                    s01_axi_awvalid,
    output wire                    s01_axi_awready,
    input  wire [DATA_WIDTH-1:0]   s01_axi_wdata,
    input  wire [DATA_WIDTH/8-1:0] s01_axi_wstrb,
    input  wire                    s01_axi_wlast,
    input  wire                    s01_axi_wvalid,
    output wire                    s01_axi_wready,
    output wire [ID_WIDTH-1:0]     s01_axi_bid,
    output wire [1:0]              s01_axi_bresp,
    output wire                    s01_axi_bvalid,
    input  wire                    s01_axi_bready,
    input  wire [ID_WIDTH-1:0]     s01_axi_arid,
    input  wire [ADDR_WIDTH-1:0]   s01_axi_araddr,
    input  wire [7:0]              s01_axi_arlen,
    input  wire [2:0]              s01_axi_arsize,
    input  wire [1:0]              s01_axi_arburst,
    input  wire                    s01_axi_arlock,
    input  wire [3:0]              s01_axi_arcache,
    input  wire [2:0]              s01_axi_arprot,
    input  wire [3:0]              s01_axi_arqos,
    input  wire                    s01_axi_arvalid,
    output wire                    s01_axi_arready,
    output wire [ID_WIDTH-1:0]     s01_axi_rid,
    output wire [DATA_WIDTH-1:0]   s01_axi_rdata,
    output wire [1:0]              s01_axi_rresp,
    output wire                    s01_axi_rlast,
    output wire                    s01_axi_rvalid,
    input  wire                    s01_axi_rready,

    // ── I2C pads ─────────────────────────────────────────────────────────
    input  wire        scl_pad_i,
    output wire        scl_pad_o,
    output wire        scl_padoen_o,
    input  wire        sda_pad_i,
    output wire        sda_pad_o,
    output wire        sda_padoen_o,
    output wire        i2c_irq,

    // ── UART pads ─────────────────────────────────────────────────────────
    output wire        uart_tx_o,
    input  wire        uart_rx_i,
    output wire        uart_irq,

    // ── VeeR trace port (optional — wire out for Verdi probing) ──────────
    output wire [31:0] trace_rv_i_insn_ip,
    output wire [31:0] trace_rv_i_address_ip,
    output wire        trace_rv_i_valid_ip,
    output wire        trace_rv_i_exception_ip,
    output wire [4:0]  trace_rv_i_ecause_ip,
    output wire        trace_rv_i_interrupt_ip,
    output wire [31:0] trace_rv_i_tval_ip
);

    // =========================================================================
    // 0.  Internal resets
    // =========================================================================
    wire rst      = ~rst_n;           // active-high for modules that need it
    wire rst_l    =  rst_n;           // active-low  for VeeR
    wire dbg_rst_l = rst_n;           // debug reset (same as system reset here)

    // =========================================================================
    // 1.  VeeR LSU AXI raw wires  (64-bit data, ID_WIDTH = `RV_LSU_BUS_TAG = 3)
    // =========================================================================
    localparam VEER_ID  = `RV_LSU_BUS_TAG;   // 3

    // -- AW channel --
    wire                  lsu_axi_awvalid;
    wire                  lsu_axi_awready;
    wire [VEER_ID-1:0]    lsu_axi_awid;
    wire [31:0]           lsu_axi_awaddr;
    wire [3:0]            lsu_axi_awregion;
    wire [7:0]            lsu_axi_awlen;
    wire [2:0]            lsu_axi_awsize;
    wire [1:0]            lsu_axi_awburst;
    wire                  lsu_axi_awlock;
    wire [3:0]            lsu_axi_awcache;
    wire [2:0]            lsu_axi_awprot;
    wire [3:0]            lsu_axi_awqos;
    // -- W channel --
    wire                  lsu_axi_wvalid;
    wire                  lsu_axi_wready;
    wire [63:0]           lsu_axi_wdata;     // 64-bit
    wire [7:0]            lsu_axi_wstrb;     // 8-bit
    wire                  lsu_axi_wlast;
    // -- B channel --
    wire                  lsu_axi_bvalid;
    wire                  lsu_axi_bready;
    wire [1:0]            lsu_axi_bresp;
    wire [VEER_ID-1:0]    lsu_axi_bid;
    // -- AR channel --
    wire                  lsu_axi_arvalid;
    wire                  lsu_axi_arready;
    wire [VEER_ID-1:0]    lsu_axi_arid;
    wire [31:0]           lsu_axi_araddr;
    wire [3:0]            lsu_axi_arregion;
    wire [7:0]            lsu_axi_arlen;
    wire [2:0]            lsu_axi_arsize;
    wire [1:0]            lsu_axi_arburst;
    wire                  lsu_axi_arlock;
    wire [3:0]            lsu_axi_arcache;
    wire [2:0]            lsu_axi_arprot;
    wire [3:0]            lsu_axi_arqos;
    // -- R channel --
    wire                  lsu_axi_rvalid;
    wire                  lsu_axi_rready;
    wire [VEER_ID-1:0]    lsu_axi_rid;
    wire [63:0]           lsu_axi_rdata;     // 64-bit
    wire [1:0]            lsu_axi_rresp;
    wire                  lsu_axi_rlast;

    // =========================================================================
    // 2.  Width-adapter: VeeR 64-bit LSU AXI  →  32-bit s00 interconnect
    //
    //  Rules:
    //   • AW/AR : pass through (address is 32-bit already, ID padded/truncated)
    //   • W     : select the correct 32-bit lane based on awaddr[2].
    //             VeeR aligns AXI addresses to 8-byte boundaries; for a 32-bit
    //             store at offset[2]=1 (e.g. 0x0C, 0x14 ...) the data is placed
    //             in wdata[63:32] / wstrb[7:4].  For offset[2]=0 it is in
    //             wdata[31:0] / wstrb[3:0].
    //   • B     : pass through
    //   • R     : rdata[63:32] returned as 0 to core (reads always word-aligned)
    //
    //  ID width mismatch: interconnect s00 uses ID_WIDTH=8, VeeR uses 3.
    //  Pad VeeR's 3-bit ID to 8-bit on master → slave direction,
    //  truncate back to 3-bit on slave → master responses.
    // =========================================================================

    // S00 32-bit AXI Bus (from 64-to-32 adapter to interconnect)
    wire [ID_WIDTH-1:0]    s00_awid;
    wire [ADDR_WIDTH-1:0]  s00_awaddr;
    wire [7:0]             s00_awlen;
    wire [2:0]             s00_awsize;
    wire [1:0]             s00_awburst;
    wire                   s00_awlock;
    wire [3:0]             s00_awcache;
    wire [2:0]             s00_awprot;
    wire [3:0]             s00_awqos;
    wire                   s00_awvalid;
    wire                   s00_awready;

    wire [DATA_WIDTH-1:0]  s00_wdata;
    wire [DATA_WIDTH/8-1:0]s00_wstrb;
    wire                   s00_wlast;
    wire                   s00_wvalid;
    wire                   s00_wready;

    wire [ID_WIDTH-1:0]    s00_bid;
    wire [1:0]             s00_bresp;
    wire                   s00_bvalid;
    wire                   s00_bready;

    wire [ID_WIDTH-1:0]    s00_arid;
    wire [ADDR_WIDTH-1:0]  s00_araddr;
    wire [7:0]             s00_arlen;
    wire [2:0]             s00_arsize;
    wire [1:0]             s00_arburst;
    wire                   s00_arlock;
    wire [3:0]             s00_arcache;
    wire [2:0]             s00_arprot;
    wire [3:0]             s00_arqos;
    wire                   s00_arvalid;
    wire                   s00_arready;

    wire [ID_WIDTH-1:0]    s00_rid;
    wire [DATA_WIDTH-1:0]  s00_rdata;
    wire [1:0]             s00_rresp;
    wire                   s00_rlast;
    wire                   s00_rvalid;
    wire                   s00_rready;

    axi_64to32_adapter #(
        .M_ID_WIDTH (VEER_ID),
        .S_ID_WIDTH (ID_WIDTH)
    ) u_lsu_adapter (
        .clk             (clk),
        .rst_l           (rst_l),

        .m_axi_awvalid   (lsu_axi_awvalid),
        .m_axi_awready   (lsu_axi_awready),
        .m_axi_awid      (lsu_axi_awid),
        .m_axi_awaddr    (lsu_axi_awaddr),
        .m_axi_awlen     (lsu_axi_awlen),
        .m_axi_awsize    (lsu_axi_awsize),
        .m_axi_awburst   (lsu_axi_awburst),
        .m_axi_awlock    (lsu_axi_awlock),
        .m_axi_awcache   (lsu_axi_awcache),
        .m_axi_awprot    (lsu_axi_awprot),
        .m_axi_awqos     (lsu_axi_awqos),
        .m_axi_awregion  (lsu_axi_awregion),
        .m_axi_wvalid    (lsu_axi_wvalid),
        .m_axi_wready    (lsu_axi_wready),
        .m_axi_wdata     (lsu_axi_wdata),
        .m_axi_wstrb     (lsu_axi_wstrb),
        .m_axi_wlast     (lsu_axi_wlast),
        .m_axi_bvalid    (lsu_axi_bvalid),
        .m_axi_bready    (lsu_axi_bready),
        .m_axi_bresp     (lsu_axi_bresp),
        .m_axi_bid       (lsu_axi_bid),
        .m_axi_arvalid   (lsu_axi_arvalid),
        .m_axi_arready   (lsu_axi_arready),
        .m_axi_arid      (lsu_axi_arid),
        .m_axi_araddr    (lsu_axi_araddr),
        .m_axi_arregion  (lsu_axi_arregion),
        .m_axi_arlen     (lsu_axi_arlen),
        .m_axi_arsize    (lsu_axi_arsize),
        .m_axi_arburst   (lsu_axi_arburst),
        .m_axi_arlock    (lsu_axi_arlock),
        .m_axi_arcache   (lsu_axi_arcache),
        .m_axi_arprot    (lsu_axi_arprot),
        .m_axi_arqos     (lsu_axi_arqos),
        .m_axi_rvalid    (lsu_axi_rvalid),
        .m_axi_rready    (lsu_axi_rready),
        .m_axi_rid       (lsu_axi_rid),
        .m_axi_rdata     (lsu_axi_rdata),
        .m_axi_rresp     (lsu_axi_rresp),
        .m_axi_rlast     (lsu_axi_rlast),

        .s_axi_awid      (s00_awid),
        .s_axi_awaddr    (s00_awaddr),
        .s_axi_awlen     (s00_awlen),
        .s_axi_awsize    (s00_awsize),
        .s_axi_awburst   (s00_awburst),
        .s_axi_awlock    (s00_awlock),
        .s_axi_awcache   (s00_awcache),
        .s_axi_awprot    (s00_awprot),
        .s_axi_awqos     (s00_awqos),
        .s_axi_awregion  (),
        .s_axi_awvalid   (s00_awvalid),
        .s_axi_awready   (s00_awready),
        .s_axi_wdata     (s00_wdata),
        .s_axi_wstrb     (s00_wstrb),
        .s_axi_wlast     (s00_wlast),
        .s_axi_wvalid    (s00_wvalid),
        .s_axi_wready    (s00_wready),
        .s_axi_bid       (s00_bid),
        .s_axi_bresp     (s00_bresp),
        .s_axi_bvalid    (s00_bvalid),
        .s_axi_bready    (s00_bready),
        .s_axi_arid      (s00_arid),
        .s_axi_araddr    (s00_araddr),
        .s_axi_arlen     (s00_arlen),
        .s_axi_arsize    (s00_arsize),
        .s_axi_arburst   (s00_arburst),
        .s_axi_arlock    (s00_arlock),
        .s_axi_arcache   (s00_arcache),
        .s_axi_arprot    (s00_arprot),
        .s_axi_arqos     (s00_arqos),
        .s_axi_arregion  (),
        .s_axi_arvalid   (s00_arvalid),
        .s_axi_arready   (s00_arready),
        .s_axi_rid       (s00_rid),
        .s_axi_rdata     (s00_rdata),
        .s_axi_rresp     (s00_rresp),
        .s_axi_rlast     (s00_rlast),
        .s_axi_rvalid    (s00_rvalid),
        .s_axi_rready    (s00_rready)
    );

    // =========================================================================
    // 3.  IFU AXI stub
    //     With ICCM enabled, the IFU never drives this port for normal
    //     instruction fetches.  We tie all slave-side ready/valid signals
    //     to 0 so the core simply never gets a response on this channel.
    //     Change these to a real instruction memory if booting from external.
    // =========================================================================
    localparam IFU_ID = `RV_IFU_BUS_TAG;   // 3

    wire                  ifu_axi_awvalid, ifu_axi_awready;
    wire [IFU_ID-1:0]     ifu_axi_awid;
    wire [31:0]           ifu_axi_awaddr;
    wire [3:0]            ifu_axi_awregion;
    wire [7:0]            ifu_axi_awlen;
    wire [2:0]            ifu_axi_awsize;
    wire [1:0]            ifu_axi_awburst;
    wire                  ifu_axi_awlock;
    wire [3:0]            ifu_axi_awcache;
    wire [2:0]            ifu_axi_awprot;
    wire [3:0]            ifu_axi_awqos;
    wire                  ifu_axi_wvalid,  ifu_axi_wready;
    wire [63:0]           ifu_axi_wdata;
    wire [7:0]            ifu_axi_wstrb;
    wire                  ifu_axi_wlast;
    wire                  ifu_axi_bvalid,  ifu_axi_bready;
    wire [1:0]            ifu_axi_bresp;
    wire [IFU_ID-1:0]     ifu_axi_bid;
    wire                  ifu_axi_arvalid, ifu_axi_arready;
    wire [IFU_ID-1:0]     ifu_axi_arid;
    wire [31:0]           ifu_axi_araddr;
    wire [3:0]            ifu_axi_arregion;
    wire [7:0]            ifu_axi_arlen;
    wire [2:0]            ifu_axi_arsize;
    wire [1:0]            ifu_axi_arburst;
    wire                  ifu_axi_arlock;
    wire [3:0]            ifu_axi_arcache;
    wire [2:0]            ifu_axi_arprot;
    wire [3:0]            ifu_axi_arqos;
    wire                  ifu_axi_rvalid,  ifu_axi_rready;
    wire [IFU_ID-1:0]     ifu_axi_rid;
    wire [63:0]           ifu_axi_rdata;
    wire [1:0]            ifu_axi_rresp;
    wire                  ifu_axi_rlast;

    // Stub: IFU AXI write channel — slave never accepts (awready/wready=0)
    assign ifu_axi_awready = 1'b0;
    assign ifu_axi_wready  = 1'b0;
    assign ifu_axi_bvalid  = 1'b0;
    assign ifu_axi_bresp   = 2'b00;
    assign ifu_axi_bid     = {IFU_ID{1'b0}};
    // Stub: IFU AXI read channel — slave never accepts
    assign ifu_axi_arready = 1'b0;
    assign ifu_axi_rvalid  = 1'b0;
    assign ifu_axi_rdata   = 64'h0;
    assign ifu_axi_rresp   = 2'b00;
    assign ifu_axi_rid     = {IFU_ID{1'b0}};
    assign ifu_axi_rlast   = 1'b0;

    // =========================================================================
    // 4.  SB (System Bus / debug) AXI — tied off
    //     Not needed for functional simulation without external debugger.
    // =========================================================================
    localparam SB_ID = `RV_SB_BUS_TAG;   // 1

    wire sb_axi_awvalid, sb_axi_awready;
    wire [SB_ID-1:0]  sb_axi_awid;
    wire [31:0]       sb_axi_awaddr;
    wire [3:0]        sb_axi_awregion;
    wire [7:0]        sb_axi_awlen;
    wire [2:0]        sb_axi_awsize;
    wire [1:0]        sb_axi_awburst;
    wire              sb_axi_awlock;
    wire [3:0]        sb_axi_awcache;
    wire [2:0]        sb_axi_awprot;
    wire [3:0]        sb_axi_awqos;
    wire              sb_axi_wvalid,  sb_axi_wready;
    wire [63:0]       sb_axi_wdata;
    wire [7:0]        sb_axi_wstrb;
    wire              sb_axi_wlast;
    wire              sb_axi_bvalid,  sb_axi_bready;
    wire [1:0]        sb_axi_bresp;
    wire [SB_ID-1:0]  sb_axi_bid;
    wire              sb_axi_arvalid, sb_axi_arready;
    wire [SB_ID-1:0]  sb_axi_arid;
    wire [31:0]       sb_axi_araddr;
    wire [3:0]        sb_axi_arregion;
    wire [7:0]        sb_axi_arlen;
    wire [2:0]        sb_axi_arsize;
    wire [1:0]        sb_axi_arburst;
    wire              sb_axi_arlock;
    wire [3:0]        sb_axi_arcache;
    wire [2:0]        sb_axi_arprot;
    wire [3:0]        sb_axi_arqos;
    wire              sb_axi_rvalid,  sb_axi_rready;
    wire [SB_ID-1:0]  sb_axi_rid;
    wire [63:0]       sb_axi_rdata;
    wire [1:0]        sb_axi_rresp;
    wire              sb_axi_rlast;

    assign sb_axi_awready = 1'b0;
    assign sb_axi_wready  = 1'b0;
    assign sb_axi_bvalid  = 1'b0;
    assign sb_axi_bresp   = 2'b00;
    assign sb_axi_bid     = {SB_ID{1'b0}};
    assign sb_axi_arready = 1'b0;
    assign sb_axi_rvalid  = 1'b0;
    assign sb_axi_rdata   = 64'h0;
    assign sb_axi_rresp   = 2'b00;
    assign sb_axi_rid     = {SB_ID{1'b0}};
    assign sb_axi_rlast   = 1'b0;

    // =========================================================================
    // 5.  DMA AXI — tied off (no external DMA in this SoC)
    // =========================================================================
    localparam DMA_ID = `RV_DMA_BUS_TAG;   // 1

    wire              dma_axi_awvalid, dma_axi_awready;
    wire [DMA_ID-1:0] dma_axi_awid;
    wire [31:0]       dma_axi_awaddr;
    wire [2:0]        dma_axi_awsize;
    wire [2:0]        dma_axi_awprot;
    wire [7:0]        dma_axi_awlen;
    wire [1:0]        dma_axi_awburst;
    wire              dma_axi_wvalid,  dma_axi_wready;
    wire [63:0]       dma_axi_wdata;
    wire [7:0]        dma_axi_wstrb;
    wire              dma_axi_wlast;
    wire              dma_axi_bvalid,  dma_axi_bready;
    wire [1:0]        dma_axi_bresp;
    wire [DMA_ID-1:0] dma_axi_bid;
    wire              dma_axi_arvalid, dma_axi_arready;
    wire [DMA_ID-1:0] dma_axi_arid;
    wire [31:0]       dma_axi_araddr;
    wire [2:0]        dma_axi_arsize;
    wire [2:0]        dma_axi_arprot;
    wire [7:0]        dma_axi_arlen;
    wire [1:0]        dma_axi_arburst;
    wire              dma_axi_rvalid,  dma_axi_rready;
    wire [DMA_ID-1:0] dma_axi_rid;
    wire [63:0]       dma_axi_rdata;
    wire [1:0]        dma_axi_rresp;
    wire              dma_axi_rlast;

    // DMA: no external master — tie master inputs to 0
    assign dma_axi_awvalid = 1'b0;
    assign dma_axi_awid    = {DMA_ID{1'b0}};
    assign dma_axi_awaddr  = 32'h0;
    assign dma_axi_awsize  = 3'b0;
    assign dma_axi_awprot  = 3'b0;
    assign dma_axi_awlen   = 8'h0;
    assign dma_axi_awburst = 2'b01;
    assign dma_axi_wvalid  = 1'b0;
    assign dma_axi_wdata   = 64'h0;
    assign dma_axi_wstrb   = 8'h0;
    assign dma_axi_wlast   = 1'b0;
    assign dma_axi_bready  = 1'b0;
    assign dma_axi_arvalid = 1'b0;
    assign dma_axi_arid    = {DMA_ID{1'b0}};
    assign dma_axi_araddr  = 32'h0;
    assign dma_axi_arsize  = 3'b0;
    assign dma_axi_arprot  = 3'b0;
    assign dma_axi_arlen   = 8'h0;
    assign dma_axi_arburst = 2'b01;
    assign dma_axi_rready  = 1'b0;

    // =========================================================================
    // 6.  VeeR EL2 core instantiation
    // =========================================================================
    // Real SRAM interface driven by behavioral SRAM models below.
    // The el2_veer_wrapper exports ICCM/DCCM/ICache control signals through
    // the el2_mem_if interface; we wire them to simple behavioral reg-array
    // RAMs so that the core can read/write instruction and data memories.
    //
    // ICache stub: tie all read-data outputs to 0 so every tag lookup misses
    // cleanly (icache bypass path always taken). Correct for ICCM-only sims.
    el2_mem_if icache_stub_if ();
    el2_mem_if real_sram_if ();

    // Icache data read: wb_packeddout_pre, wb_dout_pre_up → return 0 (all miss)
    assign icache_stub_if.wb_packeddout_pre  = '0;
    assign icache_stub_if.wb_dout_pre_up     = '0;
    // Icache tag read: ic_tag_data_raw_packed_pre, ic_tag_data_raw_pre → 0
    assign icache_stub_if.ic_tag_data_raw_packed_pre = '0;
    assign icache_stub_if.ic_tag_data_raw_pre        = '0;

    el2_veer_wrapper u_veer (
        // Clocks & Reset
        .clk        (clk),
        .rst_l      (rst_l),
        .dbg_rst_l  (dbg_rst_l),
        .rst_vec    (rst_vec),
        .nmi_int    (nmi_int),
        .nmi_vec    (nmi_vec),
        .jtag_id    (jtag_id),

        // Trace
        .trace_rv_i_insn_ip      (trace_rv_i_insn_ip),
        .trace_rv_i_address_ip   (trace_rv_i_address_ip),
        .trace_rv_i_valid_ip     (trace_rv_i_valid_ip),
        .trace_rv_i_exception_ip (trace_rv_i_exception_ip),
        .trace_rv_i_ecause_ip    (trace_rv_i_ecause_ip),
        .trace_rv_i_interrupt_ip (trace_rv_i_interrupt_ip),
        .trace_rv_i_tval_ip      (trace_rv_i_tval_ip),

`ifdef RV_BUILD_AXI4
        // LSU AXI
        .lsu_axi_awvalid  (lsu_axi_awvalid),
        .lsu_axi_awready  (lsu_axi_awready),
        .lsu_axi_awid     (lsu_axi_awid),
        .lsu_axi_awaddr   (lsu_axi_awaddr),
        .lsu_axi_awregion (lsu_axi_awregion),
        .lsu_axi_awlen    (lsu_axi_awlen),
        .lsu_axi_awsize   (lsu_axi_awsize),
        .lsu_axi_awburst  (lsu_axi_awburst),
        .lsu_axi_awlock   (lsu_axi_awlock),
        .lsu_axi_awcache  (lsu_axi_awcache),
        .lsu_axi_awprot   (lsu_axi_awprot),
        .lsu_axi_awqos    (lsu_axi_awqos),
        .lsu_axi_wvalid   (lsu_axi_wvalid),
        .lsu_axi_wready   (lsu_axi_wready),
        .lsu_axi_wdata    (lsu_axi_wdata),
        .lsu_axi_wstrb    (lsu_axi_wstrb),
        .lsu_axi_wlast    (lsu_axi_wlast),
        .lsu_axi_bvalid   (lsu_axi_bvalid),
        .lsu_axi_bready   (lsu_axi_bready),
        .lsu_axi_bresp    (lsu_axi_bresp),
        .lsu_axi_bid      (lsu_axi_bid),
        .lsu_axi_arvalid  (lsu_axi_arvalid),
        .lsu_axi_arready  (lsu_axi_arready),
        .lsu_axi_arid     (lsu_axi_arid),
        .lsu_axi_araddr   (lsu_axi_araddr),
        .lsu_axi_arregion (lsu_axi_arregion),
        .lsu_axi_arlen    (lsu_axi_arlen),
        .lsu_axi_arsize   (lsu_axi_arsize),
        .lsu_axi_arburst  (lsu_axi_arburst),
        .lsu_axi_arlock   (lsu_axi_arlock),
        .lsu_axi_arcache  (lsu_axi_arcache),
        .lsu_axi_arprot   (lsu_axi_arprot),
        .lsu_axi_arqos    (lsu_axi_arqos),
        .lsu_axi_rvalid   (lsu_axi_rvalid),
        .lsu_axi_rready   (lsu_axi_rready),
        .lsu_axi_rid      (lsu_axi_rid),
        .lsu_axi_rdata    (lsu_axi_rdata),
        .lsu_axi_rresp    (lsu_axi_rresp),
        .lsu_axi_rlast    (lsu_axi_rlast),

        // IFU AXI (stubbed)
        .ifu_axi_awvalid  (ifu_axi_awvalid),
        .ifu_axi_awready  (ifu_axi_awready),
        .ifu_axi_awid     (ifu_axi_awid),
        .ifu_axi_awaddr   (ifu_axi_awaddr),
        .ifu_axi_awregion (ifu_axi_awregion),
        .ifu_axi_awlen    (ifu_axi_awlen),
        .ifu_axi_awsize   (ifu_axi_awsize),
        .ifu_axi_awburst  (ifu_axi_awburst),
        .ifu_axi_awlock   (ifu_axi_awlock),
        .ifu_axi_awcache  (ifu_axi_awcache),
        .ifu_axi_awprot   (ifu_axi_awprot),
        .ifu_axi_awqos    (ifu_axi_awqos),
        .ifu_axi_wvalid   (ifu_axi_wvalid),
        .ifu_axi_wready   (ifu_axi_wready),
        .ifu_axi_wdata    (ifu_axi_wdata),
        .ifu_axi_wstrb    (ifu_axi_wstrb),
        .ifu_axi_wlast    (ifu_axi_wlast),
        .ifu_axi_bvalid   (ifu_axi_bvalid),
        .ifu_axi_bready   (ifu_axi_bready),
        .ifu_axi_bresp    (ifu_axi_bresp),
        .ifu_axi_bid      (ifu_axi_bid),
        .ifu_axi_arvalid  (ifu_axi_arvalid),
        .ifu_axi_arready  (ifu_axi_arready),
        .ifu_axi_arid     (ifu_axi_arid),
        .ifu_axi_araddr   (ifu_axi_araddr),
        .ifu_axi_arregion (ifu_axi_arregion),
        .ifu_axi_arlen    (ifu_axi_arlen),
        .ifu_axi_arsize   (ifu_axi_arsize),
        .ifu_axi_arburst  (ifu_axi_arburst),
        .ifu_axi_arlock   (ifu_axi_arlock),
        .ifu_axi_arcache  (ifu_axi_arcache),
        .ifu_axi_arprot   (ifu_axi_arprot),
        .ifu_axi_arqos    (ifu_axi_arqos),
        .ifu_axi_rvalid   (ifu_axi_rvalid),
        .ifu_axi_rready   (ifu_axi_rready),
        .ifu_axi_rid      (ifu_axi_rid),
        .ifu_axi_rdata    (ifu_axi_rdata),
        .ifu_axi_rresp    (ifu_axi_rresp),
        .ifu_axi_rlast    (ifu_axi_rlast),

        // SB AXI (tied off)
        .sb_axi_awvalid   (sb_axi_awvalid),
        .sb_axi_awready   (sb_axi_awready),
        .sb_axi_awid      (sb_axi_awid),
        .sb_axi_awaddr    (sb_axi_awaddr),
        .sb_axi_awregion  (sb_axi_awregion),
        .sb_axi_awlen     (sb_axi_awlen),
        .sb_axi_awsize    (sb_axi_awsize),
        .sb_axi_awburst   (sb_axi_awburst),
        .sb_axi_awlock    (sb_axi_awlock),
        .sb_axi_awcache   (sb_axi_awcache),
        .sb_axi_awprot    (sb_axi_awprot),
        .sb_axi_awqos     (sb_axi_awqos),
        .sb_axi_wvalid    (sb_axi_wvalid),
        .sb_axi_wready    (sb_axi_wready),
        .sb_axi_wdata     (sb_axi_wdata),
        .sb_axi_wstrb     (sb_axi_wstrb),
        .sb_axi_wlast     (sb_axi_wlast),
        .sb_axi_bvalid    (sb_axi_bvalid),
        .sb_axi_bready    (sb_axi_bready),
        .sb_axi_bresp     (sb_axi_bresp),
        .sb_axi_bid       (sb_axi_bid),
        .sb_axi_arvalid   (sb_axi_arvalid),
        .sb_axi_arready   (sb_axi_arready),
        .sb_axi_arid      (sb_axi_arid),
        .sb_axi_araddr    (sb_axi_araddr),
        .sb_axi_arregion  (sb_axi_arregion),
        .sb_axi_arlen     (sb_axi_arlen),
        .sb_axi_arsize    (sb_axi_arsize),
        .sb_axi_arburst   (sb_axi_arburst),
        .sb_axi_arlock    (sb_axi_arlock),
        .sb_axi_arcache   (sb_axi_arcache),
        .sb_axi_arprot    (sb_axi_arprot),
        .sb_axi_arqos     (sb_axi_arqos),
        .sb_axi_rvalid    (sb_axi_rvalid),
        .sb_axi_rready    (sb_axi_rready),
        .sb_axi_rid       (sb_axi_rid),
        .sb_axi_rdata     (sb_axi_rdata),
        .sb_axi_rresp     (sb_axi_rresp),
        .sb_axi_rlast     (sb_axi_rlast),

        // DMA AXI (tied off)
        .dma_axi_awvalid  (dma_axi_awvalid),
        .dma_axi_awready  (dma_axi_awready),
        .dma_axi_awid     (dma_axi_awid),
        .dma_axi_awaddr   (dma_axi_awaddr),
        .dma_axi_awsize   (dma_axi_awsize),
        .dma_axi_awprot   (dma_axi_awprot),
        .dma_axi_awlen    (dma_axi_awlen),
        .dma_axi_awburst  (dma_axi_awburst),
        .dma_axi_wvalid   (dma_axi_wvalid),
        .dma_axi_wready   (dma_axi_wready),
        .dma_axi_wdata    (dma_axi_wdata),
        .dma_axi_wstrb    (dma_axi_wstrb),
        .dma_axi_wlast    (dma_axi_wlast),
        .dma_axi_bvalid   (dma_axi_bvalid),
        .dma_axi_bready   (dma_axi_bready),
        .dma_axi_bresp    (dma_axi_bresp),
        .dma_axi_bid      (dma_axi_bid),
        .dma_axi_arvalid  (dma_axi_arvalid),
        .dma_axi_arready  (dma_axi_arready),
        .dma_axi_arid     (dma_axi_arid),
        .dma_axi_araddr   (dma_axi_araddr),
        .dma_axi_arsize   (dma_axi_arsize),
        .dma_axi_arprot   (dma_axi_arprot),
        .dma_axi_arlen    (dma_axi_arlen),
        .dma_axi_arburst  (dma_axi_arburst),
        .dma_axi_rvalid   (dma_axi_rvalid),
        .dma_axi_rready   (dma_axi_rready),
        .dma_axi_rid      (dma_axi_rid),
        .dma_axi_rdata    (dma_axi_rdata),
        .dma_axi_rresp    (dma_axi_rresp),
        .dma_axi_rlast    (dma_axi_rlast),
`endif // RV_BUILD_AXI4

        // JTAG
        .jtag_tck   (jtag_tck),
        .jtag_tms   (jtag_tms),
        .jtag_tdi   (jtag_tdi),
        .jtag_tdo   (jtag_tdo),

        // External interrupts — tie all to 0 for basic simulation
        .extintsrc_req ({`RV_PIC_TOTAL_INT{1'b0}}),

        // Timer interrupt — tie off
        .timer_int  (1'b0),

        // Soft interrupt — tie off
        .soft_int   (1'b0),

        // MPC halt/run interface — MUST tie mpc_reset_run_req=1 so core
        // starts running after reset (default 0 = halted after reset)
        .mpc_debug_halt_req  (1'b0),
        .mpc_debug_run_req   (1'b0),
        .mpc_reset_run_req   (1'b1),   // ← critical: 1 = run after reset
        .mpc_debug_halt_ack  (),
        .mpc_debug_run_ack   (),

        // CPU halt/run interface — tie off (no PMU in this SoC)
        .i_cpu_halt_req  (1'b0),
        .o_cpu_halt_ack  (),
        .o_cpu_halt_status (),
        .i_cpu_run_req   (1'b0),
        .o_cpu_run_ack   (),
        .o_debug_mode_status (),

        // Scan / clock-override — tie off
        .scan_mode   (1'b0),
        .mbist_mode  (1'b0),

        // Clock enables (tie high to always enable bus clocks)
        .lsu_bus_clk_en (1'b1),
        .ifu_bus_clk_en (1'b1),
        .dbg_bus_clk_en (1'b1),
        .dma_bus_clk_en (1'b1),

        // JTAG extensions
        .jtag_trst_n (rst_n),
        .jtag_tdoEn  (),
        .core_id     (28'h0),

        // Unused ECC status
        .iccm_ecc_single_error (),
        .iccm_ecc_double_error (),
        .dccm_ecc_single_error (),
        .dccm_ecc_double_error (),
        .dccm_write_readback_error (),

        // DMI Uncore (tied off)
        .dmi_core_enable   (1'b0),
        .dmi_uncore_enable (1'b0),
        .dmi_uncore_en     (),
        .dmi_uncore_wr_en  (),
        .dmi_uncore_addr   (),
        .dmi_uncore_wdata  (),
        .dmi_uncore_rdata  (32'h0),
        .dmi_active        (),

        // Export interfaces
        .el2_icache_export (icache_stub_if),
        .el2_mem_export    (real_sram_if)
    );

    // =========================================================================
    // 7.  SoC subsystem — instantiate existing soc_top
    //     s00 is driven by VeeR LSU (via width-adapter above).
    //     s01 is passed through to the top-level port.
    // =========================================================================
    soc_top #(
        .DATA_WIDTH (DATA_WIDTH),
        .ADDR_WIDTH (ADDR_WIDTH),
        .ID_WIDTH   (ID_WIDTH)
    ) u_soc (
        .clk    (clk),
        .rst_n  (rst_n),

        // Master port 0 — VeeR LSU (width-adapted to 32-bit)
        .s00_axi_awid    (s00_awid),
        .s00_axi_awaddr  (s00_awaddr),
        .s00_axi_awlen   (s00_awlen),
        .s00_axi_awsize  (s00_awsize),
        .s00_axi_awburst (s00_awburst),
        .s00_axi_awlock  (s00_awlock),
        .s00_axi_awcache (s00_awcache),
        .s00_axi_awprot  (s00_awprot),
        .s00_axi_awqos   (s00_awqos),
        .s00_axi_awvalid (s00_awvalid),
        .s00_axi_awready (s00_awready),
        .s00_axi_wdata   (s00_wdata),
        .s00_axi_wstrb   (s00_wstrb),
        .s00_axi_wlast   (s00_wlast),
        .s00_axi_wvalid  (s00_wvalid),
        .s00_axi_wready  (s00_wready),
        .s00_axi_bid     (s00_bid),
        .s00_axi_bresp   (s00_bresp),
        .s00_axi_bvalid  (s00_bvalid),
        .s00_axi_bready  (s00_bready),
        .s00_axi_arid    (s00_arid),
        .s00_axi_araddr  (s00_araddr),
        .s00_axi_arlen   (s00_arlen),
        .s00_axi_arsize  (s00_arsize),
        .s00_axi_arburst (s00_arburst),
        .s00_axi_arlock  (s00_arlock),
        .s00_axi_arcache (s00_arcache),
        .s00_axi_arprot  (s00_arprot),
        .s00_axi_arqos   (s00_arqos),
        .s00_axi_arvalid (s00_arvalid),
        .s00_axi_arready (s00_arready),
        .s00_axi_rid     (s00_rid),
        .s00_axi_rdata   (s00_rdata),
        .s00_axi_rresp   (s00_rresp),
        .s00_axi_rlast   (s00_rlast),
        .s00_axi_rvalid  (s00_rvalid),
        .s00_axi_rready  (s00_rready),

        // Master port 1 — spare (top-level port)
        .s01_axi_awid    (s01_axi_awid),
        .s01_axi_awaddr  (s01_axi_awaddr),
        .s01_axi_awlen   (s01_axi_awlen),
        .s01_axi_awsize  (s01_axi_awsize),
        .s01_axi_awburst (s01_axi_awburst),
        .s01_axi_awlock  (s01_axi_awlock),
        .s01_axi_awcache (s01_axi_awcache),
        .s01_axi_awprot  (s01_axi_awprot),
        .s01_axi_awqos   (s01_axi_awqos),
        .s01_axi_awvalid (s01_axi_awvalid),
        .s01_axi_awready (s01_axi_awready),
        .s01_axi_wdata   (s01_axi_wdata),
        .s01_axi_wstrb   (s01_axi_wstrb),
        .s01_axi_wlast   (s01_axi_wlast),
        .s01_axi_wvalid  (s01_axi_wvalid),
        .s01_axi_wready  (s01_axi_wready),
        .s01_axi_bid     (s01_axi_bid),
        .s01_axi_bresp   (s01_axi_bresp),
        .s01_axi_bvalid  (s01_axi_bvalid),
        .s01_axi_bready  (s01_axi_bready),
        .s01_axi_arid    (s01_axi_arid),
        .s01_axi_araddr  (s01_axi_araddr),
        .s01_axi_arlen   (s01_axi_arlen),
        .s01_axi_arsize  (s01_axi_arsize),
        .s01_axi_arburst (s01_axi_arburst),
        .s01_axi_arlock  (s01_axi_arlock),
        .s01_axi_arcache (s01_axi_arcache),
        .s01_axi_arprot  (s01_axi_arprot),
        .s01_axi_arqos   (s01_axi_arqos),
        .s01_axi_arvalid (s01_axi_arvalid),
        .s01_axi_arready (s01_axi_arready),
        .s01_axi_rid     (s01_axi_rid),
        .s01_axi_rdata   (s01_axi_rdata),
        .s01_axi_rresp   (s01_axi_rresp),
        .s01_axi_rlast   (s01_axi_rlast),
        .s01_axi_rvalid  (s01_axi_rvalid),
        .s01_axi_rready  (s01_axi_rready),

        // I2C
        .scl_pad_i    (scl_pad_i),
        .scl_pad_o    (scl_pad_o),
        .scl_padoen_o (scl_padoen_o),
        .sda_pad_i    (sda_pad_i),
        .sda_pad_o    (sda_pad_o),
        .sda_padoen_o (sda_padoen_o),
        .i2c_irq      (i2c_irq),

        // UART
        .uart_tx_o  (uart_tx_o),
        .uart_rx_i  (uart_rx_i),
        .uart_irq   (uart_irq)
    );

    // =========================================================================
    // 8.  Behavioral ICCM / DCCM SRAM models
    //
    //  el2_veer_wrapper exports ICCM and DCCM memory control through
    //  el2_mem_export (el2_mem_if).  In simulation we supply simple
    //  synchronous-read behavioral reg-array RAMs for each bank so the
    //  CPU can actually fetch instructions and load/store data.
    //
    //  ICCM: 4 banks x 4096 rows x 39 bits (32-bit data + 7-bit ECC)
    //        Configured by RV_ICCM_NUM_BANKS_4 / RV_ICCM_ROWS = 4096
    //        RV_ICCM_INDEX_BITS = 12  →  addr[13:2] = 12 bits → 4096 rows
    //
    //  DCCM: 4 banks x 4096 rows x 39 bits (32-bit data + 7-bit ECC)
    //
    //  The VCS +define+ICCM_HIER_LOAD path for the testbench is:
    //    dut.Gen_iccm_enable.iccm_loop[N].iccm_bank.ram_core
    //
    //  NOTE: icache is also driven through el2_icache_export; we leave that
    //  dummy because ICCM-mode firmware does not need the I$ to run.
    // =========================================================================

    // =========================================================================
    // 8.  Behavioral ICCM / DCCM SRAM models
    //
    //  Uses the official VeeR EL2 ram_4096x39 behavioral model from mem_lib.sv
    //  (already compiled via the -v ../rtl/Cores-VeeR-EL2/design/lib/mem_lib.sv
    //  entry in the filelist).  This guarantees timing compatibility with VeeR.
    //
    //  ICCM: 4 banks × 4096 rows × 39 bits (32-bit data + 7-bit ECC)
    //  DCCM: 4 banks × 4096 rows × 39 bits (32-bit data + 7-bit ECC)
    //
    //  Hierarchical path for TB $readmemh (data portion):
    //    dut.Gen_iccm_enable.iccm_loop[N].iccm_bank.ram_core
    // =========================================================================

    // ------------------------------------------------------------------
    // ICCM banks
    // ------------------------------------------------------------------
    localparam ICCM_ROWS  = `RV_ICCM_ROWS;
    localparam DCCM_ROWS  = `RV_DCCM_ROWS;

    // Registered ECC-with-data merged write data per bank
    wire [`RV_ICCM_NUM_BANKS-1:0][38:0] iccm_wr_fdata;
    wire [`RV_ICCM_NUM_BANKS-1:0][38:0] iccm_bank_fdout;
    wire [`RV_DCCM_NUM_BANKS-1:0][38:0] dccm_wr_fdata;
    wire [`RV_DCCM_NUM_BANKS-1:0][38:0] dccm_bank_fdout;

    if (`RV_ICCM_ENABLE) begin : Gen_iccm_enable
        for (genvar i = 0; i < `RV_ICCM_NUM_BANKS; i++) begin : iccm_loop
            assign iccm_wr_fdata[i] = {real_sram_if.iccm_bank_wr_ecc[i],
                                        real_sram_if.iccm_bank_wr_data[i]};

            ram_4096x39 iccm_bank (
                .CLK (real_sram_if.clk),
                .ME  (real_sram_if.iccm_clken[i]),
                .WE  (real_sram_if.iccm_wren_bank[i]),
                .ADR (real_sram_if.iccm_addr_bank[i]),
                .D   (iccm_wr_fdata[i]),
                .Q   (iccm_bank_fdout[i]),
                .ROP (),
                .TEST1    (1'b0), .RME (1'b0), .RM (4'b0),
                .LS (1'b0), .DS (1'b0), .SD (1'b0),
                .TEST_RNM (1'b0), .BC1 (1'b0), .BC2 (1'b0)
            );

            assign real_sram_if.iccm_bank_dout[i] = iccm_bank_fdout[i][31:0];
            assign real_sram_if.iccm_bank_ecc[i]  = iccm_bank_fdout[i][38:32];
        end
    end else begin : Gen_iccm_disable
        assign real_sram_if.iccm_bank_dout = '0;
        assign real_sram_if.iccm_bank_ecc  = '0;
    end

    // ------------------------------------------------------------------
    // DCCM banks
    // ------------------------------------------------------------------
    if (`RV_DCCM_ENABLE) begin : Gen_dccm_enable
        for (genvar j = 0; j < `RV_DCCM_NUM_BANKS; j++) begin : dccm_loop
            assign dccm_wr_fdata[j] = {real_sram_if.dccm_wr_ecc_bank[j],
                                        real_sram_if.dccm_wr_data_bank[j]};

            ram_4096x39 dccm_bank (
                .CLK (real_sram_if.clk),
                .ME  (real_sram_if.dccm_clken[j]),
                .WE  (real_sram_if.dccm_wren_bank[j]),
                .ADR (real_sram_if.dccm_addr_bank[j]),
                .D   (dccm_wr_fdata[j]),
                .Q   (dccm_bank_fdout[j]),
                .ROP (),
                .TEST1    (1'b0), .RME (1'b0), .RM (4'b0),
                .LS (1'b0), .DS (1'b0), .SD (1'b0),
                .TEST_RNM (1'b0), .BC1 (1'b0), .BC2 (1'b0)
            );

            assign real_sram_if.dccm_bank_dout[j] = dccm_bank_fdout[j][31:0];
            assign real_sram_if.dccm_bank_ecc[j]  = dccm_bank_fdout[j][38:32];
        end
    end else begin : Gen_dccm_disable
        assign real_sram_if.dccm_bank_dout = '0;
        assign real_sram_if.dccm_bank_ecc  = '0;
    end

    // NOTE: real_sram_if.clk is driven by el2_mem.sv internally
    // (assign mem_export.clk = clk inside el2_mem) — do NOT drive it here.

endmodule
`default_nettype wire
